# Site Settings
title: Ignatov CV
url: "https://github.com/metamorfoso/curriculum-vitae.github.io.git"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from
